#!/bin/sh

set -e

commands='help repl build watch'

help() {
	echo >&2 'usage: ./dev COMMAND [OPTIONS...]'
	echo >&2 "  available commands: $commands"
}

repl() {
	shift
	exec clj -A:repl
}

build() {
	shift
	exec clojure -A:build
}

watch() {
	shift
	exec clojure -A:watch
}

die() {
	help
	exit 1
}

[ "$#" -ge 1 ] || die

command="$1"
found_command=false
for c in $commands; do
	[ "$c" = "$command" ] && {
		found_command=true
		"$c" "$@"
	}
done

[ "$found_command" = true ] || die
