#!/bin/env python3

import os
import sys


def build():
    raise NotImplementedError

def repl(*extra_args):
    cmdline = 'clj -Afig -m figwheel.main --build repl --repl'.split()
    os.execvp(cmdline[0], cmdline + list(extra_args))


if __name__ == '__main__':
    _, command_name, *args = sys.argv
    command = globals().get(command_name)
    
    if not command:
        print(f'error: no command named {command_name}', file=sys.stderr)
        exit(1)

    command(*args)
