#!/bin/env python3

import os
import sys


def build(*extra_args):
    # cmdline = 'your build command'.split()
    # os.execvp(cmdline[0], cmdline + list(extra_args))
    raise NotImplementedError

if __name__ == '__main__':
    _, command_name, *args = sys.argv
    command = globals().get(command_name)
    
    if not command:
        print(f'error: no command named {command_name}', file=sys.stderr)
        exit(1)

    command(*args)
