#!/bin/sh

set -e

commands='help build'

help() {
	echo >&2 'usage: ./dev COMMAND [OPTIONS...]'
	echo >&2 "  available commands: $commands"
}

build() {
	shift  # remove the command name from $@
	# write code to build your project
}

die() {
	help
	exit 1
}

[ "$#" -ge 1 ] || die

command="$1"
found_command=false
for c in $commands; do
	[ "$c" = "$command" ] && {
		found_command=true
		"$c" "$@"
	}
done

[ "$found_command" = true ] || die
